import type { ComponentMeta } from '@lowcode/types';

export const TableMeta: ComponentMeta = {
  name: 'DataTable',
  label: '数据表格',
  icon: 'TableOutlined',
  category: 'business',
  defaultProps: {
    columns: [],
    dataSource: [],
    rowKey: 'id',
    variant: 'outlined',
    bordered: false,
    striped: false,
    pagination: true,
    pageSize: 20,
    showSizeChanger: true,
    showQuickJumper: true,
    showHeader: true,
    size: 'middle',
    scroll: undefined,
    rowSelection: false,
    loading: false,
    exportCSV: false,
    showRefresh: false,
    dataSourceId: '',
    tableName: '',
  },
  propSchema: [
    {
      name: 'columns',
      label: '列配置',
      type: 'array',
      defaultValue: [],
      group: 'data',
    },
    {
      name: 'dataSourceId',
      label: '数据源 ID',
      type: 'string',
      defaultValue: '',
      group: 'data',
    },
    {
      name: 'tableName',
      label: '数据库表名',
      type: 'string',
      defaultValue: '',
      group: 'data',
    },
    {
      name: 'rowKey',
      label: '行 Key 字段',
      type: 'string',
      defaultValue: 'id',
      group: 'basic',
    },
    {
      name: 'variant',
      label: '边框样式',
      type: 'select',
      options: [
        { label: '有边框', value: 'outlined' },
        { label: '无边框', value: 'borderless' },
        { label: '填充', value: 'filled' },
      ],
      defaultValue: 'outlined',
      group: 'style',
    },
    {
      name: 'striped',
      label: '斑马纹',
      type: 'boolean',
      defaultValue: false,
      group: 'style',
    },
    {
      name: 'pagination',
      label: '分页',
      type: 'boolean',
      defaultValue: true,
      group: 'pagination',
    },
    {
      name: 'pageSize',
      label: '每页条数',
      type: 'number',
      defaultValue: 20,
      group: 'pagination',
    },
    {
      name: 'showSizeChanger',
      label: '可切换每页条数',
      type: 'boolean',
      defaultValue: true,
      group: 'pagination',
    },
    {
      name: 'showQuickJumper',
      label: '显示快速跳转',
      type: 'boolean',
      defaultValue: true,
      group: 'pagination',
    },
    {
      name: 'showHeader',
      label: '显示表头',
      type: 'boolean',
      defaultValue: true,
      group: 'basic',
    },
    {
      name: 'size',
      label: '尺寸',
      type: 'select',
      options: [
        { label: '大', value: 'large' },
        { label: '中', value: 'middle' },
        { label: '小', value: 'small' },
      ],
      defaultValue: 'middle',
      group: 'basic',
    },
    {
      name: 'rowSelection',
      label: '可选择',
      type: 'boolean',
      defaultValue: false,
      group: 'basic',
    },
    {
      name: 'exportCSV',
      label: '显示导出 CSV',
      type: 'boolean',
      defaultValue: false,
      group: 'toolbar',
    },
    {
      name: 'showRefresh',
      label: '显示刷新按钮',
      type: 'boolean',
      defaultValue: false,
      group: 'toolbar',
    },
    {
      name: 'loading',
      label: '加载中',
      type: 'boolean',
      defaultValue: false,
      group: 'basic',
    },
  ],
  eventSchema: [
    { name: 'onChange', label: '变化', description: '分页、排序、筛选变化时触发' },
    { name: 'onRowClick', label: '行点击', description: '点击行时触发' },
    { name: 'onSelectChange', label: '选择变化', description: '选择项变化时触发' },
    { name: 'onCellSave', label: '单元格保存', description: '行内编辑保存时触发' },
  ],
  styleSchema: [],
};
