import type { ComponentMeta } from '@lowcode/types';

export const TableMeta: ComponentMeta = {
  name: 'DataTable',
  label: '数据表格',
  icon: 'TableOutlined',
  category: 'business',
  defaultProps: {
    columns: [],
    dataSource: [],
    rowKey: 'id',
    bordered: false,
    striped: false,
    pagination: true,
    pageSize: 10,
    showHeader: true,
    size: 'middle',
    scroll: undefined,
    rowSelection: false,
    loading: false,
  },
  propSchema: [
    {
      name: 'columns',
      label: '列配置',
      type: 'array',
      defaultValue: [],
      group: 'data',
    },
    {
      name: 'rowKey',
      label: '行 Key 字段',
      type: 'string',
      defaultValue: 'id',
      group: 'basic',
    },
    {
      name: 'bordered',
      label: '带边框',
      type: 'boolean',
      defaultValue: false,
      group: 'style',
    },
    {
      name: 'striped',
      label: '斑马纹',
      type: 'boolean',
      defaultValue: false,
      group: 'style',
    },
    {
      name: 'pagination',
      label: '分页',
      type: 'boolean',
      defaultValue: true,
      group: 'basic',
    },
    {
      name: 'pageSize',
      label: '每页条数',
      type: 'number',
      defaultValue: 10,
      group: 'basic',
    },
    {
      name: 'showHeader',
      label: '显示表头',
      type: 'boolean',
      defaultValue: true,
      group: 'basic',
    },
    {
      name: 'size',
      label: '尺寸',
      type: 'select',
      options: [
        { label: '大', value: 'large' },
        { label: '中', value: 'middle' },
        { label: '小', value: 'small' },
      ],
      defaultValue: 'middle',
      group: 'basic',
    },
    {
      name: 'rowSelection',
      label: '可选择',
      type: 'boolean',
      defaultValue: false,
      group: 'basic',
    },
    {
      name: 'loading',
      label: '加载中',
      type: 'boolean',
      defaultValue: false,
      group: 'basic',
    },
  ],
  eventSchema: [
    { name: 'onChange', label: '变化', description: '分页、排序、筛选变化时触发' },
    { name: 'onRowClick', label: '行点击', description: '点击行时触发' },
    { name: 'onSelectChange', label: '选择变化', description: '选择项变化时触发' },
  ],
  styleSchema: [],
};
