import type { ComponentMeta } from '@lowcode/types';

export const InputMeta: ComponentMeta = {
  name: 'Input',
  label: '输入框',
  icon: 'InputOutlined',
  category: 'basic',
  defaultProps: {
    placeholder: '请输入',
    type: 'text',
    size: 'middle',
    disabled: false,
    allowClear: true,
    showCount: false,
    maxLength: undefined,
    prefix: undefined,
    suffix: undefined,
  },
  propSchema: [
    {
      name: 'type',
      label: '输入类型',
      type: 'select',
      options: [
        { label: '文本', value: 'text' },
        { label: '密码', value: 'password' },
        { label: '数字', value: 'number' },
        { label: '邮箱', value: 'email' },
        { label: '搜索', value: 'search' },
        { label: '网址', value: 'url' },
        { label: '电话', value: 'tel' },
      ],
      defaultValue: 'text',
      group: 'basic',
    },
    {
      name: 'placeholder',
      label: '占位符',
      type: 'string',
      defaultValue: '请输入',
      group: 'basic',
    },
    {
      name: 'size',
      label: '尺寸',
      type: 'select',
      options: [
        { label: '大', value: 'large' },
        { label: '中', value: 'middle' },
        { label: '小', value: 'small' },
      ],
      defaultValue: 'middle',
      group: 'basic',
    },
    {
      name: 'disabled',
      label: '禁用',
      type: 'boolean',
      defaultValue: false,
      group: 'basic',
    },
    {
      name: 'allowClear',
      label: '可清除',
      type: 'boolean',
      defaultValue: true,
      group: 'basic',
    },
    {
      name: 'showCount',
      label: '显示字数',
      type: 'boolean',
      defaultValue: false,
      group: 'basic',
    },
    {
      name: 'maxLength',
      label: '最大长度',
      type: 'number',
      defaultValue: undefined,
      group: 'basic',
    },
    {
      name: 'prefix',
      label: '前缀',
      type: 'string',
      defaultValue: undefined,
      group: 'basic',
    },
    {
      name: 'suffix',
      label: '后缀',
      type: 'string',
      defaultValue: undefined,
      group: 'basic',
    },
  ],
  eventSchema: [
    { name: 'onChange', label: '值变化', description: '输入值变化时触发' },
    { name: 'onPressEnter', label: '回车', description: '按下回车键时触发' },
    { name: 'onFocus', label: '获得焦点', description: '获得焦点时触发' },
    { name: 'onBlur', label: '失去焦点', description: '失去焦点时触发' },
  ],
  styleSchema: [
    { name: 'width', label: '宽度', type: 'string', defaultValue: '100%' },
  ],
};
