import type { ComponentMeta } from '@lowcode/types';

export const TextMeta: ComponentMeta = {
  name: 'Text',
  label: '文本',
  icon: 'FontSizeOutlined',
  category: 'basic',
  defaultProps: {
    content: '这是一段文本',
    type: 'secondary',
    level: 1,
    strong: false,
    italic: false,
    underline: false,
    delete: false,
    mark: false,
    code: false,
  },
  propSchema: [
    {
      name: 'content',
      label: '文本内容',
      type: 'string',
      defaultValue: '这是一段文本',
      group: 'basic',
    },
    {
      name: 'type',
      label: '类型',
      type: 'select',
      options: [
        { label: '主要文本', value: 'primary' },
        { label: '次要文本', value: 'secondary' },
        { label: '成功文本', value: 'success' },
        { label: '警告文本', value: 'warning' },
        { label: '错误文本', value: 'danger' },
        { label: '禁用文本', value: 'disabled' },
      ],
      defaultValue: 'secondary',
      group: 'basic',
    },
    {
      name: 'level',
      label: '标题级别',
      type: 'select',
      options: [
        { label: '普通文本', value: 0 },
        { label: '标题1', value: 1 },
        { label: '标题2', value: 2 },
        { label: '标题3', value: 3 },
        { label: '标题4', value: 4 },
        { label: '标题5', value: 5 },
      ],
      defaultValue: 0,
      group: 'basic',
    },
    {
      name: 'strong',
      label: '加粗',
      type: 'boolean',
      defaultValue: false,
      group: 'basic',
    },
    {
      name: 'italic',
      label: '斜体',
      type: 'boolean',
      defaultValue: false,
      group: 'basic',
    },
    {
      name: 'underline',
      label: '下划线',
      type: 'boolean',
      defaultValue: false,
      group: 'basic',
    },
    {
      name: 'delete',
      label: '删除线',
      type: 'boolean',
      defaultValue: false,
      group: 'basic',
    },
    {
      name: 'mark',
      label: '标记',
      type: 'boolean',
      defaultValue: false,
      group: 'basic',
    },
    {
      name: 'code',
      label: '代码',
      type: 'boolean',
      defaultValue: false,
      group: 'basic',
    },
  ],
  eventSchema: [],
  styleSchema: [
    { name: 'color', label: '颜色', type: 'color' },
    { name: 'fontSize', label: '字号', type: 'string', defaultValue: '14px' },
    { name: 'textAlign', label: '对齐', type: 'select', options: [
      { label: '左对齐', value: 'left' },
      { label: '居中', value: 'center' },
      { label: '右对齐', value: 'right' },
    ]},
  ],
};
